title:  <p align="center"> Punyanuch Chenyawanich </p>

logo: "/pic/MYSELF.jpg"

description: |
  <p align="center">
    <a href="/pdf/CV.pdf">CV</a> |
    <a href="www.linkedin.com/in/punyanuch-chenyawanich">LinkedIn</a> 
  </p>

  <p align="justify">
    I am a recent Statistics graduate from the Faculty of Science with experience in applying statistical methods for data analysis. With a strong core in Python and Stata, I am always ready to learn new skills and am currently exploring roles in Data Science and Data Analytics to begin my career journey.
theme: jekyll-theme-minimal


